defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

markdown_ext: "markdown,md"

exclude:
- Gemfile
- Gemfile.lock
- README.md

sass:
  sass_dir: _sass

collections:
  posts:
    permalink: pretty
  works:
    output: true
    permalink: /works/:path/
  about:
    output: true
    permalink: /about/:path/
  texts:
    output: true
    permalink: /texts/:path/
  scores:
    permalink: /scores/:path/
    output: true
